CREATE TABLE IF NOT EXISTS contact_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reference_code CHAR(5) NULL,
    request_type VARCHAR(32) NOT NULL,
    name VARCHAR(150) NOT NULL,
    organisation VARCHAR(200) NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(60) NULL,
    subject VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    privacy_acknowledged_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'new',
    notification_sent_at DATETIME NULL,
    notification_failed_at DATETIME NULL,
    confirmation_sent_at DATETIME NULL,
    confirmation_failed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_contact_reference_code (reference_code),
    KEY idx_contact_created_at (created_at),
    KEY idx_contact_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_verifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reference_code VARCHAR(64) NOT NULL,
    public_title VARCHAR(200) NOT NULL,
    public_partner VARCHAR(200) NULL,
    public_client VARCHAR(200) NULL,
    valid_from DATE NULL,
    valid_until DATE NULL,
    confidentiality_mode ENUM('public','confidential') NOT NULL DEFAULT 'public',
    public_note TEXT NULL,
    person_name VARCHAR(150) NULL,
    role_label VARCHAR(120) NULL,
    agency_name VARCHAR(200) NULL,
    project_name VARCHAR(200) NULL,
    brand_name VARCHAR(200) NULL,
    photo_asset VARCHAR(255) NULL,
    brand_logo_asset VARCHAR(255) NULL,
    agency_logo_asset VARCHAR(255) NULL,
    scope_key VARCHAR(80) NULL,
    document_asset VARCHAR(255) NULL,
    document_label VARCHAR(200) NULL,
    document_enabled TINYINT(1) NOT NULL DEFAULT 0,
    print_card_enabled TINYINT(1) NOT NULL DEFAULT 0,
    is_personal_verification TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_audit_reference_code (reference_code),
    KEY idx_audit_active (is_active),
    KEY idx_audit_valid_until (valid_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS verify_rate_limits (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ip_hash CHAR(64) NOT NULL,
    attempted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_verify_rate_ip_time (ip_hash, attempted_at),
    KEY idx_verify_rate_attempted_at (attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
